export interface AnalysisEvidence { href: string; start_ms: number; end_ms: number; segment_id: string; label: string }
export interface AnalysisScore { value: number | null; low?: number | null; high?: number | null; uncertainty?: string; coverage?: number | null; confidence?: number | null; heterogeneity?: number | null; probabilities?: Record<string, number> | null; evidence?: AnalysisEvidence[] }
export type AnalysisDisplayScore = Omit<AnalysisScore,'value'> & {value?:number|null;choice?:string|null};
export interface AnalysisQuestion { id: string; short_name: string; domain: string; instructions: string; criteria: string[] | Record<string,string>; type: 'score'|'choice'|'noul'; factor_eligible: boolean; applicability?: string; sources?: string[] }
export interface AnalysisVideo { recording_id: string; revision_id: string; title: string; href: string; date: string | null; date_basis: string; category: string | null; coverage: number; scored_passage?: AnalysisEvidence | null; question_scores: Record<string, AnalysisScore | number | null>; factor_scores: Record<string, {value:number;low:number|null;high:number|null;uncertainty:'bootstrap_stability'|'bootstrap_stability_unavailable'} | null>; classifications?: Record<string,{choice:string|null;probabilities:Record<string,number>;confidence:number|null;coverage:number|null}>; noul_scores?: Record<string,number|null> }
export interface AnalysisRelease { schema_version: 1; status: 'pilot' | 'complete'; corpus_release_id: string; questionnaire_version: string; model: string; generated_at: string; coverage: { total_recordings: number; scored_recordings: number; total_chunks: number; scored_chunks: number }; questions: AnalysisQuestion[]; videos: AnalysisVideo[]; analysis: { status: 'insufficient_data' | 'exploratory'; n: number; question_ids: string[]; factor_question_ids: string[]; primary_factor_n?: number | null; correlations: (number | null)[][]; pair_counts: number[][]; mds: {id:string;x:number;y:number}[]; mds_stress: number | null; mds_method: string; factors: {id:string;label:string;loadings:Record<string,number|null>;loading_intervals:Record<string,[number,number]|null>}[]; diagnostics: Record<string, unknown> } }
export function validateAnalysisRelease(value: unknown): AnalysisRelease;
export function scoreFor(video: AnalysisVideo, id: string, kind: 'question' | 'factor' | 'classification'): AnalysisDisplayScore | null;
export function filterAndSortVideos(videos: AnalysisVideo[], filters: Record<string,string>, kind: 'question' | 'factor' | 'classification', metric: string): AnalysisVideo[];
export function groupTimeSeries(videos: AnalysisVideo[], metric: string, kind: 'question' | 'factor' | 'classification', interval?: 'year' | 'month'): {period:string;x:number;mean:number;low:number|null;high:number|null;n:number;coverage:number|null}[];
export function trendInterpretation(kind: 'question' | 'factor' | 'classification', questionType?: 'score' | 'choice' | 'noul'): string;
export function largestFactorLoadings(factor: AnalysisRelease['analysis']['factors'][number], questions: AnalysisQuestion[], limit?: number): {question_id:string;short_name:string;loading:number}[];
export function hrefAtTime(href: string, milliseconds: number, revisionId?: string, segmentId?: string): string;
